name: Pact tests

on: pull_request

permissions:
  contents: read

jobs:
  install-and-compile:
    runs-on: ubuntu-18.04
    name: Install and compile

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 12.22.1
      - name: Cache build directories
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            govuk_modules
            public
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}
      - name: Cache NPM packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Cache Cypress
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress
      - name: Install dependencies
        run: npm ci
      - name: Compile
        run: npm run compile
      - name: Run lint
        run: npm run lint

  unit-tests:
    runs-on: ubuntu-18.04
    name: Unit tests
    needs: install-and-compile

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 12.22.1
      - name: Cache build directories
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            govuk_modules
            public
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}
      - name: Run unit tests
        run: npm test -- --forbid-only --forbid-pending
      - name: Publish pacts
        uses: ./publish-pacts
        with:
          pact-broker-username: ${{ secrets.PactBrokerUsername }}
          pact-broker-password: ${{ secrets.PactBrokerPassword }}
          consumer: selfservice
          consumer-sha: ${{ github.sha }}
          pr-id: ${{ github.event.number }}

  cypress-tests:
    runs-on: ubuntu-18.04
    name: Cypress tests
    needs: install-and-compile

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 12.22.1
      - name: Cache build directories
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            govuk_modules
            public
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}
      - name: Cache Cypress
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress
      - name: Run cypress tests
        run: |
          npm run cypress:server > /dev/null 2>&1 &
          sleep 3
          npm run cypress:test

  pact-provider-tests:
    name: Pact provider verification
    runs-on: ubuntu-18.04
    needs: unit-tests

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get providers needing verfication
        id: get-providers
        ## These actions will live in a different repository but are added locally for demonstration
        uses: ./actions/get-pact-providers-needing-validation
        with:
          pact-broker-username: ${{ secrets.PactBrokerUsername }}
          pact-broker-password: ${{ secrets.PactBrokerPassword }}
          consumer: selfservice
          consumer-tag: ${{ github.sha }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Pull docker images
        run: docker pull govukpay/postgres:11.1
      - name: Checkout ledger master
        uses: actions/checkout@v2
        with:
          repository: alphagov/pay-ledger
          path: ledger
      - name: Cache Ledger Maven packages
        uses: actions/cache@v2
        with:
          path: ledger/.m2
          key: ${{ runner.os }}-ledger-m2-${{ hashFiles('ledger/pom.xml') }}
          restore-keys: ${{ runner.os }}-ledger-m2
      - name: Run pact provider tests
        uses: ./actions/pact-provider-tests
        with:
          pact-broker-username: ${{ secrets.PactBrokerUsername }}
          pact-broker-password: ${{ secrets.PactBrokerPassword }}
          consumer: selfservice
          consumer-tag: ${{ github.sha }}
          provider: ledger
          providers-needing-validation: ${{ steps.get-providers.outputs.providers-needing-validation }}
      - name: Checkout adminusers master
        uses: actions/checkout@v2
        with:
          repository: alphagov/pay-adminusers
          path: adminusers
      - name: Cache Adminusers Maven packages
        uses: actions/cache@v2
        with:
          path: adminusers/.m2
          key: ${{ runner.os }}-adminusers-m2-${{ hashFiles('adminusers/pom.xml') }}
          restore-keys: ${{ runner.os }}-adminusers-m2
      - name: Run pact provider tests
        uses: ./actions/pact-provider-tests
        with:
          pact-broker-username: ${{ secrets.PactBrokerUsername }}
          pact-broker-password: ${{ secrets.PactBrokerPassword }}
          consumer: selfservice
          consumer-tag: ${{ github.sha }}
          provider: adminusers
          providers-needing-validation: ${{ steps.get-providers.outputs.providers-needing-validation }}
